Added basic login and Sign up forms
pgayee694/menui pull request #14
Opened 2019-11-04 18:40 UTC by cheddartot

basic, unformated HTML pages added with sign up and login forms, values passed to routes.py for use in API later

2019-11-04 19:51 UTC, pgayee694 requested changes
Looks good, just a few changes

2019-11-04 19:51 UTC, pgayee694 commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
stuff in ide specific folders (like the .idea folder) should not be commited

2019-11-04 19:51 UTC, pgayee694 commented on app/forms.py
> +from flask_wtf import FlaskForm
add flask_wtf to requirements.txt

2019-11-04 19:51 UTC, pgayee694 commented on app/routes.py
> +@app.route('/signup/', methods=['GET', 'POST'])
have a blank line between functions

2019-11-04 19:51 UTC, pgayee694 commented on app/templates/login.html
> +    <!DOCTYPE html>
fix indentation in this file

2019-11-04 19:51 UTC, pgayee694 commented on app/templates/signup.html
> + <!DOCTYPE html>
fix indentation in this file

2019-11-04 19:51 UTC, pgayee694 commented on app/forms.py
> +    password = PasswordField('PasswordSignUp', validators=[DataRequired()])
These field names show up really weird on the the web-page. These could probably be changed to 'Username' and 'Password' respectively

2019-11-17 22:50 UTC, pgayee694 approved these changes

2019-11-17 22:55 UTC, tkorisko approved these changes
All looks good, but add location form on signup.

2019-11-17 23:49 UTC, bbuffington1662 approved these changes

2019-11-17 23:54 UTC, merged