Friends
pgayee694/menui pull request #42
Opened 2019-12-07 20:56 UTC by cheddartot

2019-12-07 23:15 UTC, pgayee694 requested changes

2019-12-07 23:15 UTC, pgayee694 commented on app/routes.py
> +    db.create_all()
you shouldn't need this here, this already runs in the app's init

2019-12-08 06:09 UTC, pgayee694 approved these changes

2019-12-08 22:33 UTC, tkorisko approved these changes

2019-12-08 23:24 UTC, merged